title: 犬でもわかる暗号技術入門
description: 暗号とは何か犬でもわかるように説明します！
theme: just-the-docs

url: https://akakou-docs.github.io/crypto

aux_links:
  Template Repository: https://github.com/akakou-docs/crypto


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
search_enabled: false
